theme = "jetbrains_dark"

[editor]
line-number = "relative"
mouse = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true
max-wrap = 25

[keys.normal]
# Saves the buffer and sends "node <file>" to the right tmux pane
"C-r" = [
  ":w",
  ":sh tmux send-keys -t .{right} 'clear; nub %{buffer_name}' Enter"
]

"C-s" = [":w"]
"C-w" = [":bc"]

"A-k" = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
"A-j" = ["extend_to_line_bounds", "delete_selection", "paste_after"]

[keys.insert]
"C-s" = [":w"]
"C-w" = [":bc"]

[keys.select]
"C-s" = [":w"]
"C-w" = [":bc"]
"A-k" = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
"A-j" = ["extend_to_line_bounds", "delete_selection", "paste_after"]
